exp_name: "TEST_ES"

case_study: "SweetReactor"

init_pop_path: "/data/compounds/ecoli_sink.tsv"
init_pop_size: 10

rules_path: "/data/reactionrules/retrorules/retrorules_rr02_flat_all_forward.tsv"
max_rules_by_iter: 100
use_coreactant_info: False
coreactants_path: "/path/..."

multi_objective: False
batched: True
generations: 10
algorithm: "ES"
verbose: False
visualize: False
