exp_name: "TEST_MUTATOR"

case_study: "SweetReactor"

init_pop_path: "/data/compounds/ecoli_sink.tsv"
init_pop_size: 100

rules_path: "/data/reactionrules/all_rules/all_reaction_rules.tsv"
max_rules_by_iter: 1000
use_coreactant_info: True
coreactants_path: "/data/reactionrules/all_rules/all_coreactants.tsv"

multi_objective: True
batched: True
generations: 100
algorithm: "NSGAIII"
verbose: False
visualize: True
