exp_name: "TEST_Visualization"

case_study: "CompoundQuality"

init_pop_path: "/data/compounds/ecoli_sink.tsv"
init_pop_size: 100

rules_path: "/data/reactionrules/retrorules/retrorules_rr02_flat_all_forward.tsv"
max_rules_by_iter: 1000
use_coreactant_info: False
coreactants_path: "/path/..."

multi_objective: True
batched: True
generations: 100
algorithm: "NSGAIII"
verbose: False
visualize: True
