exp_name: "###Report_NSGAIII_v4_100_35gen_3"

case_study: "SweetReactor"

init_pop_path: "data/compounds/ecoli_sink.tsv"
init_pop_size: 10

max_rules_by_iter: 10
tolerance: 0.15

multi_objective: True
batched: True
generations: 2
algorithm: "NSGAIII"
verbose: False
visualize: False

output_path: "outputs/"
